apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-app-postgres-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: todo-app
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: todo-app
        app.kubernetes.io/component: database
    spec:
      containers:
      - name: postgres
        image: postgres:11.2
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: todo-app-database-secret
                key: POSTGRES_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: todo-app-database-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: todo-app-database-secret
                key: POSTGRES_DATABASE_NAME
